package_id: "devicemanager_0-1-0-fake"
meta:
    creator: "Taylor Somann"
    last modified: "March 26th, 2019"
    description: "Device management daemon"
commands: 
    broadcastclient:
        cmd: ['docker', 'image.tar', 'pkg_broadcast_client', ['<id>', '<remote>']]
applications:
    - 'Broadcast Client'
bindings: []
